### ISSUE TITLE
How to consume application/xml

### ISSUE THREAD

**Issue by Nox-404** [krakenjs/hapi-openapi#131]
Hello,
when I try to consume application/xml I only get a Unsupported Media Type
Is there a way to set onPostAuth on some routes to convert those XML into JSON to avoid that problem ?

**Comment by tlivings** [comment]
I suspect because hapi does not provide application/xml parsing support.

However, I believe a change is required in this module to disable parsing on unhandled media types so that they can be parsed manually. 

Although I shudder at xml in Node.js ;) I will label this as an enhancement and address the above.

**Comment by tlivings** [comment]
`x-hapi-options` can be used on the route to disable parsing FYI.

**Comment by Nox-404** [comment]
I'll close the issue, x-hapi-options works for me
